import type { IndustryProfile } from "../profile";

// Gulf facility-management company: commercial and residential buildings in the UAE.
export const facilities: IndustryProfile = {
  key: "facilities",
  label: "Facility management",
  orgName: "Crescent Facilities",
  accent: "#14a38b",
  managerTitle: "Head of Operations",
  timezone: "Asia/Dubai",
  terms: { site: "Building", sites: "Buildings", technician: "Engineer", technicians: "Engineers" },
  siteSize: { unit: "m²", label: "under management" },
  people: [
    { fullName: "Sarah Mitchell", phone: "+971 50 000 3301" },
    { fullName: "Rajesh Kumar", phone: "+971 50 000 3302" },
    { fullName: "Mohammed Al Mansoori", phone: "+971 50 000 3303" },
    { fullName: "Grace Otieno", phone: "+971 50 000 3304" },
    { fullName: "Joseph Mensah", phone: "+971 50 000 3305" },
    { fullName: "Arjun Nair", phone: "+971 50 000 3306" },
    { fullName: "Layla Hassan", phone: "+971 50 000 3307" },
    { fullName: "Omar Haddad", phone: "+971 50 000 3308" },
  ],
  sites: [
    { code: "DXB-MH", name: "Marina Heights Tower", city: "Dubai", address: "Dubai Marina", latitude: 25.0806, longitude: 55.1403, size: 42000 },
    { code: "DXB-BB", name: "Business Bay Offices", city: "Dubai", address: "Marasi Drive, Business Bay", latitude: 25.1857, longitude: 55.2721, size: 28500 },
    { code: "AUH-AR", name: "Al Reem Residences", city: "Abu Dhabi", address: "Al Reem Island", latitude: 24.4989, longitude: 54.4066, size: 36000 },
    { code: "DXB-CW", name: "City Walk Retail Centre", city: "Dubai", address: "Al Wasl Rd", latitude: 25.2066, longitude: 55.2619, size: 61000 },
    { code: "DXB-AQ", name: "Al Quoz Logistics Park", city: "Dubai", address: "Al Quoz Industrial Area 3", latitude: 25.1383, longitude: 55.2275, size: 54000 },
    { code: "SHJ-UC", name: "University City Campus", city: "Sharjah", address: "University City Rd", latitude: 25.3106, longitude: 55.4825, size: 33000 },
  ],
  assetTypes: [
    { name: "Chiller", interval: 30 },
    { name: "Air handling unit", interval: 60 },
    { name: "Lift", interval: 30 },
    { name: "Fire pump", interval: 90 },
    { name: "Standby generator", interval: 45 },
  ],
  assets: [
    { tag: "CH-02", name: "Chiller 2", type: 0, manufacturer: "Carrier", model: "AquaEdge 23XRV" },
    { tag: "CH-03", name: "Chiller 3", type: 0, manufacturer: "Carrier", model: "AquaEdge 23XRV" },
    { tag: "AHU-L2-04", name: "AHU level 2 east", type: 1, manufacturer: "Trane", model: "CLCP 40" },
    { tag: "LFT-A1", name: "Passenger lift A1", type: 2, manufacturer: "Otis", model: "Gen2" },
    { tag: "AHU-R-01", name: "Rooftop AHU", type: 1, manufacturer: "Daikin", model: "D-AHU Modular" },
    { tag: "GEN-BB1", name: "Standby generator", type: 4, manufacturer: "Caterpillar", model: "C18 600 kVA" },
    { tag: "FP-BB1", name: "Main fire pump", type: 3, manufacturer: "Grundfos", model: "NKF 150" },
    { tag: "AHU-T1-02", name: "Tower 1 AHU", type: 1, manufacturer: "Trane", model: "CLCP 30" },
    { tag: "LFT-T1-3", name: "Tower 1 lift 3", type: 2, manufacturer: "Schindler", model: "5500" },
    { tag: "LFT-W2", name: "Warehouse goods lift", type: 2, manufacturer: "KONE", model: "TranSys" },
    { tag: "FP-AQ1", name: "Sprinkler fire pump", type: 3, manufacturer: "Grundfos", model: "NKF 100" },
    { tag: "CH-UC1", name: "Campus chiller 1", type: 0, manufacturer: "York", model: "YVAA" },
    { tag: "AHU-UC-07", name: "Library AHU", type: 1, manufacturer: "Daikin", model: "D-AHU Modular" },
    { tag: "GEN-AQ1", name: "Standby generator", type: 4, manufacturer: "Cummins", model: "C1100 D5" },
  ],
  issues: [
    { title: "Chiller tripped on high head pressure", description: "CH-02 tripped and won't reset. Condenser fans running but coil heavily fouled. Mall concourse at 29°C and rising, with the lunchtime peak in 90 minutes." },
    { title: "Generator day-tank leak", description: "Slow diesel weep at the day-tank outlet fitting. Drip tray placed; fitting needs replacing." },
    { title: "AHU belt slipping — noisy operation", description: "Belt glazed and squealing on start-up. Airflow 15% below design." },
    { title: "Goods lift stopping between floors", description: "Two entrapments this week. Door lock contact suspected." },
    { title: "AHU filters overdue", description: "Differential pressure high on the pre-filters." },
  ],
  workOrders: [
    "Planned preventive maintenance — CH-02",
    "Replace generator day-tank fitting",
    "Lift monthly service — LFT-A1",
    "Belt and pulley inspection — AHU-L2-04",
    "Investigate goods lift stoppages — LFT-W2",
    "Quarterly building audit — Sharjah campus",
    "Replace AHU pre-filters",
    "Generator load bank test — GEN-BB1",
    "Fire pump weekly run test",
  ],
  maintenance: [
    "PPM visit — chiller trip found, issue raised",
    "Condenser coil chemical clean",
    "Quarterly inspection — all checks passed",
    "Installed and handed over by contractor",
    "Day-tank fitting leak logged",
    "Load bank test — 2 hrs at 75%",
    "Pre-filters replaced, pressure normal",
    "Belt glazing noted, tension adjusted",
  ],
};
