import type { IndustryProfile } from "../profile";

// Oilfield services contractor maintaining production facilities in the Niger Delta.
export const oilGas: IndustryProfile = {
  key: "oil-gas",
  label: "Oil & gas services",
  orgName: "Deltaline Energy Services",
  accent: "#2f6fed",
  managerTitle: "Maintenance Superintendent",
  timezone: "Africa/Lagos",
  terms: { site: "Facility", sites: "Facilities", technician: "Technician", technicians: "Technicians" },
  people: [
    { fullName: "Tamuno Briggs", phone: "+234 806 000 4401" },
    { fullName: "Efe Oghene", phone: "+234 806 000 4402" },
    { fullName: "Ebi Tonye", phone: "+234 806 000 4403" },
    { fullName: "Uduak Etim", phone: "+234 806 000 4404" },
    { fullName: "Ifeanyi Obi", phone: "+234 806 000 4405" },
    { fullName: "Blessing Akpan", phone: "+234 806 000 4406" },
    { fullName: "Tobi Alade", phone: "+234 806 000 4407" },
    { fullName: "David Horsfall", phone: "+234 806 000 4408" },
  ],
  sites: [
    { code: "RV-ONB", name: "Onne Supply Base", city: "Onne", address: "Onne Oil & Gas Free Zone", latitude: 4.7236, longitude: 7.1519 },
    { code: "RV-PHC", name: "Trans-Amadi Workshop", city: "Port Harcourt", address: "Trans-Amadi Industrial Layout", latitude: 4.8156, longitude: 7.0498 },
    { code: "DT-UGH", name: "Ughelli Metering Station", city: "Ughelli", address: "Ughelli–Patani Rd", latitude: 5.4899, longitude: 6.0047 },
    { code: "DT-WRR", name: "Warri Flow Station", city: "Warri", address: "Warri–Sapele Rd", latitude: 5.5544, longitude: 5.7932 },
    { code: "AK-EKT", name: "Eket Pumping Station", city: "Eket", address: "Eket–Oron Rd", latitude: 4.6423, longitude: 7.9244 },
    { code: "RV-BNY", name: "Bonny Storage Depot", city: "Bonny", address: "Bonny Island", latitude: 4.4516, longitude: 7.1705 },
  ],
  assetTypes: [
    { name: "Pump", interval: 30 },
    { name: "Gas compressor", interval: 45 },
    { name: "Pressure vessel", interval: 180 },
    { name: "Gas generator", interval: 45 },
    { name: "Fire & gas system", interval: 90 },
  ],
  assets: [
    { tag: "P-104", name: "Crude transfer pump", type: 0, manufacturer: "Flowserve", model: "HPX 6x4" },
    { tag: "P-105", name: "Crude transfer pump (standby)", type: 0, manufacturer: "Flowserve", model: "HPX 6x4" },
    { tag: "V-210", name: "HP production separator", type: 2, manufacturer: "Worthington", model: "3-phase 1,200 psi" },
    { tag: "FG-331", name: "Fire & gas panel", type: 4, manufacturer: "Honeywell", model: "Searchpoint" },
    { tag: "P-044", name: "Fresh-water pump", type: 0, manufacturer: "Grundfos", model: "CR 64" },
    { tag: "GG-012", name: "Workshop gas generator", type: 3, manufacturer: "Caterpillar", model: "G3512" },
    { tag: "K-118", name: "Air compressor", type: 1, manufacturer: "Atlas Copco", model: "GA 90" },
    { tag: "FG-402", name: "Gas detection loop", type: 4, manufacturer: "Dräger", model: "Polytron 8700" },
    { tag: "V-077", name: "Metering skid vessel", type: 2, manufacturer: "Emerson", model: "Daniel 3818" },
    { tag: "K-150", name: "Gas lift compressor", type: 1, manufacturer: "Ariel", model: "JGK/4" },
    { tag: "P-520", name: "Booster pump", type: 0, manufacturer: "Sulzer", model: "MSD 4x6" },
    { tag: "FG-515", name: "Tank farm F&G panel", type: 4, manufacturer: "Honeywell", model: "Searchpoint" },
    { tag: "P-305", name: "Loading pump", type: 0, manufacturer: "KSB", model: "HGM 3/6" },
    { tag: "GG-031", name: "Station gas generator", type: 3, manufacturer: "Waukesha", model: "VHP P9390" },
  ],
  issues: [
    { title: "Mechanical seal leak — pump isolated", description: "P-104 outboard seal leaking crude at roughly 2 L/min. Pump isolated and standby P-105 started. Standby has 340 hrs since last service. Bund containing the spill." },
    { title: "Gas generator exhaust leak", description: "Exhaust manifold gasket leaking at cylinder bank B. CO reading 45 ppm at 1 m." },
    { title: "Separator level transmitter drifting", description: "LT-210 reading 6% higher than the sight glass. Recalibration needed." },
    { title: "Compressor high discharge temperature", description: "Stage 2 discharge at 152°C against a 145°C trip setpoint. Cooler fouling suspected." },
    { title: "Gas detector calibration overdue", description: "Three heads past their 90-day bump-test interval." },
  ],
  workOrders: [
    "Routine inspection — P-104",
    "Replace generator exhaust gasket",
    "Monthly F&G function test",
    "Recalibrate LT-210 on V-210",
    "Clean stage 2 cooler — K-150",
    "Quarterly HSE walkdown — Bonny depot",
    "Bump-test gas detectors",
    "Generator 1,000-hr service — GG-012",
    "Booster pump vibration survey",
  ],
  maintenance: [
    "Routine inspection — seal leak found, issue raised",
    "Bearing replacement and alignment",
    "Quarterly inspection — all checks passed",
    "Installed and commissioned",
    "Exhaust leak logged, CO monitored",
    "1,000-hr service: oil, plugs, filters",
    "Detectors bump-tested and certified",
    "Level transmitter drift noted",
  ],
};
