import type { IndustryProfile } from "../profile";

export const solar: IndustryProfile = {
  key: "solar",
  label: "Solar & mini-grids",
  orgName: "SunGrid Energy",
  accent: "#e8a317",
  managerTitle: "Operations Manager",
  timezone: "Africa/Lagos",
  terms: { site: "Site", sites: "Sites", technician: "Technician", technicians: "Technicians" },
  siteSize: { unit: "kW", label: "installed" },
  people: [
    { fullName: "Adaeze Okafor", phone: "+234 803 000 1101" },
    { fullName: "Tunde Bakare", phone: "+234 803 000 1102" },
    { fullName: "Emeka Nwosu", phone: "+234 803 000 1103" },
    { fullName: "Fatima Bello", phone: "+234 803 000 1104" },
    { fullName: "Kelechi Eze", phone: "+234 803 000 1105" },
    { fullName: "Seyi Adeyemi", phone: "+234 803 000 1106" },
    { fullName: "Ngozi Umeh", phone: "+234 803 000 1107" },
    { fullName: "Ibrahim Musa", phone: "+234 803 000 1108" },
  ],
  sites: [
    { code: "LAG-01", name: "Lekki Commercial Hub", city: "Lagos", address: "Admiralty Way, Lekki Phase 1", latitude: 6.4474, longitude: 3.4723, size: 480 },
    { code: "LAG-02", name: "Ikeja Industrial Park", city: "Lagos", address: "Oba Akran Ave, Ikeja", latitude: 6.6018, longitude: 3.3515, size: 750 },
    { code: "OYO-01", name: "Ibadan Cold Storage", city: "Ibadan", address: "Ring Road, Ibadan", latitude: 7.3775, longitude: 3.947, size: 320 },
    { code: "DEL-01", name: "Warri Mini-Grid", city: "Warri", address: "Effurun–Sapele Rd, Warri", latitude: 5.5544, longitude: 5.7932, size: 1200 },
    { code: "RIV-01", name: "Trans-Amadi Plant", city: "Port Harcourt", address: "Trans-Amadi Industrial Layout", latitude: 4.8156, longitude: 7.0498, size: 900 },
    { code: "FCT-01", name: "Abuja Office Campus", city: "Abuja", address: "Central Business District", latitude: 9.0579, longitude: 7.4951, size: 400 },
  ],
  assetTypes: [
    { name: "Inverter", interval: 90 },
    { name: "Battery bank", interval: 60 },
    { name: "PV array", interval: 30 },
    { name: "Backup generator", interval: 45 },
    { name: "Smart meter", interval: 180 },
  ],
  assets: [
    { tag: "INV-104", name: "Central inverter 104", type: 0, manufacturer: "Huawei", model: "SUN2000-100KTL" },
    { tag: "INV-105", name: "Central inverter 105", type: 0, manufacturer: "Huawei", model: "SUN2000-100KTL" },
    { tag: "BAT-210", name: "Battery bank A", type: 1, manufacturer: "BYD", model: "Battery-Box HVM" },
    { tag: "PV-331", name: "Rooftop array North", type: 2, manufacturer: "Jinko", model: "Tiger Neo 580W" },
    { tag: "INV-044", name: "String inverter 044", type: 0, manufacturer: "SMA", model: "Sunny Tripower 25" },
    { tag: "GEN-012", name: "Backup generator", type: 3, manufacturer: "Perkins", model: "500 kVA" },
    { tag: "BAT-118", name: "Battery bank B", type: 1, manufacturer: "Pylontech", model: "Force H2" },
    { tag: "PV-402", name: "Ground-mount array", type: 2, manufacturer: "Longi", model: "Hi-MO 6" },
    { tag: "INV-077", name: "Hybrid inverter 077", type: 0, manufacturer: "Victron", model: "Quattro 15kVA" },
    { tag: "INV-150", name: "Central inverter 150", type: 0, manufacturer: "Sungrow", model: "SG110CX" },
    { tag: "MTR-520", name: "Export meter", type: 4, manufacturer: "Hexing", model: "HXE310" },
    { tag: "PV-515", name: "Carport array", type: 2, manufacturer: "Jinko", model: "Tiger Neo 580W" },
    { tag: "BAT-305", name: "Battery bank C", type: 1, manufacturer: "BYD", model: "Battery-Box HVS" },
    { tag: "GEN-031", name: "Standby generator", type: 3, manufacturer: "Cummins", model: "C250 D5" },
  ],
  issues: [
    { title: "Inverter overheating — tripped offline", description: "INV-104 cabinet reading 78°C. Intake fan not spinning, dust build-up on filter. Unit tripped and is not restarting." },
    { title: "Generator coolant leak", description: "Small coolant leak under radiator hose clamp. Topped up; needs clamp replacement." },
    { title: "Battery cell imbalance", description: "Cell 14 is 0.18V below pack average. Monitor over next charge cycle." },
    { title: "Inverter fault code F-032 intermittent", description: "Grid overvoltage fault logged 6 times this week." },
    { title: "Panel soiling on east rows", description: "Heavy dust on rows E1–E6. Output down ~9% vs. west rows." },
  ],
  workOrders: [
    "Routine inspection — INV-104",
    "Replace generator hose clamp",
    "Monthly PV array cleaning",
    "Battery health check — BAT-210",
    "Investigate F-032 fault on INV-150",
    "Quarterly inspection — Abuja campus",
    "Clean east PV rows",
    "Generator service — GEN-012",
    "Meter calibration check",
  ],
  maintenance: [
    "Routine inspection — overheating found, issue raised",
    "Firmware update to latest release",
    "Quarterly inspection — all checks passed",
    "Commissioned and connected to mini-grid bus",
    "Coolant leak found at radiator hose",
    "Oil and filter change (250 hrs)",
    "East rows cleaned, output restored",
    "Cell imbalance detected on cell 14",
  ],
};
