import type { IndustryProfile } from "../profile";

// Pan-African tower company: sites across six countries.
export const telecom: IndustryProfile = {
  key: "telecom",
  label: "Telecom towers",
  orgName: "Meridian Towers",
  accent: "#7c5cff",
  managerTitle: "Regional NOC Manager",
  timezone: "Africa/Lagos",
  terms: { site: "Tower site", sites: "Tower sites", technician: "Technician", technicians: "Technicians" },
  people: [
    { fullName: "Amara Diallo", phone: "+234 809 000 2201" },
    { fullName: "Kwame Asante", phone: "+233 24 000 2202" },
    { fullName: "Brian Otieno", phone: "+254 712 000 203" },
    { fullName: "Aline Uwase", phone: "+250 788 000 204" },
    { fullName: "Mwila Banda", phone: "+260 97 000 2205" },
    { fullName: "Chidi Okoro", phone: "+234 809 000 2206" },
    { fullName: "Yao Kouassi", phone: "+225 07 00 00 2207" },
    { fullName: "Samuel Mensah", phone: "+233 24 000 2208" },
  ],
  sites: [
    { code: "NG-LOS-0142", name: "Lekki Phase 1 Rooftop", city: "Lagos, Nigeria", address: "Admiralty Way, Lekki", latitude: 6.4474, longitude: 3.4723 },
    { code: "GH-ACC-0087", name: "Tema Industrial Mast", city: "Accra, Ghana", address: "Community 1, Tema", latitude: 5.6698, longitude: -0.0166 },
    { code: "CI-ABJ-0310", name: "Plateau Greenfield", city: "Abidjan, Côte d'Ivoire", address: "Le Plateau, Abidjan", latitude: 5.3238, longitude: -4.0203 },
    { code: "KE-KSM-0231", name: "Kisumu Rural Hub", city: "Kisumu, Kenya", address: "Kisumu–Busia Rd", latitude: -0.0917, longitude: 34.768 },
    { code: "ZM-LUN-0055", name: "Lusaka East Mast", city: "Lusaka, Zambia", address: "Great East Rd, Lusaka", latitude: -15.3875, longitude: 28.3228 },
    { code: "RW-KGL-0019", name: "Kigali Heights Rooftop", city: "Kigali, Rwanda", address: "KG 7 Ave, Kigali", latitude: -1.9536, longitude: 30.0928 },
  ],
  assetTypes: [
    { name: "Diesel generator", interval: 30 },
    { name: "Rectifier", interval: 90 },
    { name: "Battery bank", interval: 60 },
    { name: "Solar hybrid system", interval: 60 },
    { name: "Shelter AC", interval: 90 },
  ],
  assets: [
    { tag: "GEN-4471", name: "Primary generator", type: 0, manufacturer: "Perkins", model: "15 kVA" },
    { tag: "RCT-4472", name: "Rectifier cabinet", type: 1, manufacturer: "Eltek", model: "Flatpack2 48V" },
    { tag: "BAT-4473", name: "Backup battery string", type: 2, manufacturer: "Narada", model: "48V 600Ah" },
    { tag: "SOL-1420", name: "Rooftop solar hybrid", type: 3, manufacturer: "Huawei", model: "TP48200A" },
    { tag: "RCT-1421", name: "Rectifier cabinet", type: 1, manufacturer: "Delta", model: "DPR 2900" },
    { tag: "GEN-0871", name: "Primary generator", type: 0, manufacturer: "FG Wilson", model: "P22-6" },
    { tag: "BAT-0872", name: "Backup battery string", type: 2, manufacturer: "Shoto", model: "48V 400Ah" },
    { tag: "SOL-3101", name: "Ground solar array", type: 3, manufacturer: "Huawei", model: "TP48200A" },
    { tag: "RCT-3102", name: "Rectifier cabinet", type: 1, manufacturer: "Eltek", model: "Flatpack2 48V" },
    { tag: "AC-0551", name: "Shelter air conditioner", type: 4, manufacturer: "Daikin", model: "FTXS-35" },
    { tag: "BAT-0552", name: "Backup battery string", type: 2, manufacturer: "Narada", model: "48V 600Ah" },
    { tag: "SOL-0191", name: "Rooftop solar hybrid", type: 3, manufacturer: "ZTE", model: "ZXDU68" },
    { tag: "BAT-0192", name: "Lithium battery string", type: 2, manufacturer: "Huawei", model: "ESM-48100" },
    { tag: "GEN-0553", name: "Standby generator", type: 0, manufacturer: "Cummins", model: "C22 D5" },
  ],
  issues: [
    { title: "Generator failed to start — site running on batteries", description: "GEN-4471 cranks but won't fire after grid outage. Batteries at 38% with ~1h40m autonomy left. Two tenant operators on this site; SLA breach risk." },
    { title: "Fuel discrepancy — 180 L unaccounted for", description: "Tank sensor shows a 180 L drop overnight with no generator run hours logged. Tank lock found damaged." },
    { title: "Battery autonomy below target", description: "Discharge test gave 1h40m against a 4h target. Two cells reading low." },
    { title: "Shelter temperature 41°C — AC tripping", description: "AC compressor cycling off every 10–15 minutes. Rectifier derating risk." },
    { title: "Solar array output down 12%", description: "Dust and bird droppings on panels after dry season." },
  ],
  workOrders: [
    "Preventive maintenance visit — GEN-4471",
    "Fuel reconciliation and tank lock replacement",
    "Solar panel cleaning — Lekki rooftop",
    "Battery autonomy retest — BAT-4473",
    "Replace shelter AC compressor",
    "Quarterly site audit — Kigali",
    "Clean ground solar array",
    "Generator 250-hr service — GEN-0871",
    "Battery health check — BAT-0552",
  ],
  maintenance: [
    "PM visit — generator failed to start, issue raised",
    "Controller firmware updated, auto-start re-tested",
    "Quarterly inspection — all checks passed",
    "Installed and commissioned with remote monitoring",
    "Fuel level discrepancy logged (180 L)",
    "250-hr service: oil, filters, belts",
    "Array cleaned, yield restored",
    "Autonomy test: 1h40m vs 4h target",
  ],
};
